export type BookingType = 'barbearia' | 'clinica' | 'petshop'

export const bookingData = {
  barbearia: {
    title: 'Sistema de agendamento para barbearias',
    subtitle: 'Controle serviços, barbeiros, horários e clientes em uma agenda online simples, moderna e pronta para WhatsApp.',
    business: 'Barbearia Estilo Prime',
    segment: 'Barbearia',
    highlight: 'Agenda online para organizar atendimentos e reduzir horários perdidos.',
    whatsapp: 'https://wa.me/5511961111894?text=Ol%C3%A1%2C%20vi%20a%20demo%20de%20barbearia%20e%20quero%20um%20sistema%20assim.',
    services: [
      { name: 'Corte Masculino', price: 'R$ 45', duration: '40 min' },
      { name: 'Corte + Barba', price: 'R$ 70', duration: '1h' },
      { name: 'Barba Completa', price: 'R$ 40', duration: '30 min' },
      { name: 'Sobrancelha', price: 'R$ 20', duration: '15 min' },
    ],
    professionals: [
      {
        name: 'Carlos Silva',
        role: 'Barbeiro especialista',
        rating: '4.9',
        image: '/demo/barbearia/carlitoss.jpg',
        bio: 'Especialista em degradê, barba e acabamento.',
      },
      {
        name: 'Rafael Souza',
        role: 'Barbeiro master',
        rating: '4.8',
        image: '/demo/barbearia/rafael.jpg',
        bio: 'Especialista em cortes modernos e navalha.',
      },
      {
        name: 'André Lima',
        role: 'Barbeiro estilista',
        rating: '4.7',
        image: '/demo/barbearia/andre.jpg',
        bio: 'Criativo e atento aos detalhes.',
      },
    ],
    dates: [
      { label: 'Hoje', status: '3 horários disponíveis' },
      { label: 'Amanhã', status: '5 horários disponíveis' },
      { label: 'Sexta-feira', status: '2 horários disponíveis' },
      { label: 'Sábado', status: 'Quase lotado' },
    ],
    timeSlots: [
      { time: '09:00', status: 'Disponível', available: true },
      { time: '10:00', status: 'Disponível', available: true },
      { time: '11:00', status: 'Quase lotado', available: true },
      { time: '14:00', status: 'Disponível', available: true },
      { time: '15:00', status: 'Reservado', available: false },
      { time: '16:00', status: 'Disponível', available: true },
    ],
    times: ['09:00', '10:00', '11:00', '14:00', '15:00', '16:00'],
    availableDates: ['Hoje', 'Amanhã', 'Sexta-feira', 'Sábado'],
    extras: [
      'Lembrete por WhatsApp',
      'Confirmação automática',
      'Reagendamento facilitado',
    ],
    clientFields: ['Nome', 'WhatsApp'],
    info: [
      { label: '⚠️ Lembrete', value: 'Confirmar 1h antes' },
      { label: '⏱️ Duração média', value: '45 min' },
      { label: '🔄 Reagendamento', value: 'Até 2h antes' },
    ],
    features: [
      'Escolha de serviço',
      'Seleção de barbeiro',
      'Horários disponíveis',
      'Resumo do agendamento',
      'Contato via WhatsApp',
    ],
  },

  clinica: {
    title: 'Sistema de agendamento para clínicas',
    subtitle: 'Organize consultas, profissionais, pacientes e retornos com uma experiência clara e confiável.',
    business: 'Clínica Saúde+',
    segment: 'Clínica',
    highlight: 'Agenda médica online para reduzir confusão e melhorar o atendimento.',
    whatsapp: 'https://wa.me/5511961111894?text=Ol%C3%A1%2C%20vi%20a%20demo%20de%20cl%C3%ADnica%20e%20quero%20um%20sistema%20assim.',
    services: [
      { name: 'Consulta médica', price: 'R$ 120', duration: '40 min' },
      { name: 'Avaliação especializada', price: 'R$ 90', duration: '30 min' },
      { name: 'Retorno de consulta', price: 'R$ 70', duration: '25 min' },
      { name: 'Sessão de fisioterapia', price: 'R$ 100', duration: '50 min' },
    ],
    professionals: [
      {
        name: 'Dra. Ana Martins',
        role: 'Clínica geral',
        rating: '4.9',
        image: '/demo/clinica/ana.jpg',
        bio: 'Especialista em atendimento humanizado.',
      },
      {
        name: 'Dr. Carlos Oliveira',
        role: 'Cardiologista',
        rating: '4.8',
        image: '/demo/clinica/carlos.jpg',
        bio: 'Prevenção e tratamento cardiovascular.',
      },
      {
        name: 'Dra. Juliana Silva',
        role: 'Dermatologista',
        rating: '4.9',
        image: '/demo/clinica/juliana.jpg',
        bio: 'Cuidados com a pele e estética médica.',
      },
    ],
    dates: [
      { label: 'Hoje', status: '2 horários disponíveis' },
      { label: 'Amanhã', status: '4 horários disponíveis' },
      { label: 'Sexta-feira', status: '3 horários disponíveis' },
      { label: 'Sábado', status: 'Lotado' },
    ],
    timeSlots: [
      { time: '08:00', status: 'Disponível', available: true },
      { time: '09:00', status: 'Disponível', available: true },
      { time: '10:00', status: 'Quase lotado', available: true },
      { time: '13:00', status: 'Disponível', available: true },
      { time: '14:00', status: 'Reservado', available: false },
      { time: '15:00', status: 'Disponível', available: true },
    ],
    times: ['08:00', '09:00', '10:00', '13:00', '14:00', '15:00'],
    availableDates: ['Hoje', 'Amanhã', 'Sexta-feira', 'Sábado'],
    extras: [
      'Lembrete por WhatsApp',
      'Confirmação automática',
      'Reagendamento facilitado',
    ],
    clientFields: ['Nome', 'WhatsApp', 'Convênio', 'Observação'],
    info: [
      { label: '📋 Documentos', value: 'Levar carteirinha' },
      { label: '⏱️ Duração média', value: '40 min' },
      { label: '🔄 Cancelamento', value: 'Até 4h antes' },
    ],
    features: [
      'Agendamento de consultas',
      'Escolha de profissional',
      'Controle de pacientes',
      'Retornos organizados',
      'Confirmação por WhatsApp',
    ],
  },

  petshop: {
    title: 'Sistema de agendamento para petshops',
    subtitle: 'Facilite reservas de banho, tosa e consultas, mantendo clientes, pets e horários organizados.',
    business: 'PetCare Agenda',
    segment: 'Petshop',
    highlight: 'Agenda online para petshops que precisam organizar atendimentos com praticidade.',
    whatsapp: 'https://wa.me/5511961111894?text=Ol%C3%A1%2C%20vi%20a%20demo%20de%20petshop%20e%20quero%20um%20sistema%20assim.',
    services: [
      { name: 'Banho completo', price: 'R$ 50', duration: '1h' },
      { name: 'Tosa higiênica', price: 'R$ 60', duration: '1h' },
      { name: 'Banho + Tosa', price: 'R$ 90', duration: '1h30' },
      { name: 'Consulta veterinária', price: 'R$ 120', duration: '40 min' },
    ],
    professionals: [
      {
        name: 'Equipe Pet',
        role: 'Equipe especializada',
        rating: '4.8',
        image: '/demo/petshop/equipe.jpg',
        bio: 'Profissionais treinados para seu pet.',
      },
      {
        name: 'Dr. Carlos Vet',
        role: 'Veterinário',
        rating: '4.9',
        image: '/demo/petshop/carlos.jpg',
        bio: 'Atendimento clínico e preventivo.',
      },
      {
        name: 'Juliana Groomer',
        role: 'Especialista em tosa',
        rating: '4.8',
        image: '/demo/petshop/juliana.jpg',
        bio: 'Tosa e estética animal.',
      },
    ],
    dates: [
      { label: 'Hoje', status: '4 horários disponíveis' },
      { label: 'Amanhã', status: '6 horários disponíveis' },
      { label: 'Sexta-feira', status: '2 horários disponíveis' },
      { label: 'Sábado', status: 'Quase lotado' },
    ],
    timeSlots: [
      { time: '09:00', status: 'Disponível', available: true },
      { time: '10:30', status: 'Disponível', available: true },
      { time: '12:00', status: 'Quase lotado', available: true },
      { time: '14:30', status: 'Disponível', available: true },
      { time: '16:00', status: 'Reservado', available: false },
    ],
    times: ['09:00', '10:30', '12:00', '14:30', '16:00'],
    availableDates: ['Hoje', 'Amanhã', 'Sexta-feira', 'Sábado'],
    extras: [
      'Lembrete por WhatsApp',
      'Confirmação automática',
      'Reagendamento facilitado',
    ],
    clientFields: ['Nome', 'WhatsApp', 'Nome do pet', 'Porte', 'Observação'],
    info: [
      { label: '🐾 Vacinas', value: 'Obrigatórias em dia' },
      { label: '⏱️ Duração média', value: '1 hora' },
      { label: '📝 Observação', value: 'Levar guia e coleira' },
    ],
    features: [
      'Cadastro do pet',
      'Serviços de banho e tosa',
      'Agenda por horário',
      'Controle de clientes',
      'Confirmação no WhatsApp',
    ],
  },
}